realsense2_camera:
  ros__parameters:
    camera_name: camera
    camera_namespace: camera

    enable_color: true
    enable_depth: true
    enable_gyro: true
    enable_accel: true

    depth_module.profile: 640x480x30
    color_module.profile: 640x480x30

    align_depth.enable: true

    pointcloud.enable: false
    enable_sync: true
    publish_tf: true

    unite_imu_method: 1
    gyro_fps: 200
    accel_fps: 63

    enable_infra1: false
    enable_infra2: false
